import type { LucideIcon } from 'lucide-react';
import {
  Braces, Database, Minimize2,
  FileCode, AlignLeft, SlidersHorizontal, FileJson, BookOpen, Table2, Workflow, Settings2, Container, Server, Globe, ScrollText,
  Code2, Link, Key, Ampersand, Binary, Hexagon, Calculator, Radio, Languages, Mail, Shuffle, FileArchive, Signature, FileSearch,
  Search, Type, ArrowLeftRight,
  Hash, Fingerprint, Clock, FileUp, AlignJustify, WholeWord, ArrowUpAZ, FlipHorizontal2, Link2, Eraser, Quote, Replace, Filter, Columns3, FileCode2, FileText, Sparkles, GitCompareArrows, GraduationCap, ListX, MessageSquareText,
  Boxes, Barcode, KeyRound, BookText, ShieldCheck, TimerReset, Lock, LockKeyhole, KeySquare, FileBadge, Terminal, ShieldAlert, ShieldHalf, Bot, FileCog, Dna,
  Ruler, Coins, Percent, Proportions, Cpu, Waves, Landmark, Sigma, Repeat, Grid3x3, BarChart3, Palette,
  FileType2, ShieldQuestion, FileSpreadsheet, FileJson2, Route,
} from 'lucide-react';

export interface Tool {
  id: string;
  name: string;
  description: string;
  categoryId: string;
  icon: LucideIcon;
}

export interface Category {
  id: string;
  name: string;
}

export const CATEGORIES: Category[] = [
  { id: 'formatters', name: 'Formatters & Minifiers' },
  { id: 'encoders', name: 'Encoders & Decoders' },
  { id: 'text', name: 'Regex & Text' },
  { id: 'generators', name: 'Security & Generators' },
  { id: 'numbers', name: 'Numbers & Math' },
  { id: 'data', name: 'Data & Code' },
];

export const TOOLS: Tool[] = [
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format and validate JSON with configurable indentation',
    categoryId: 'formatters',
    icon: Braces,
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    description: 'Transform messy SQL into clean, structured queries',
    categoryId: 'formatters',
    icon: Database,
  },
  {
    id: 'html-css-minifier',
    name: 'HTML / CSS Minifier',
    description: 'Strip spaces and comments from HTML and CSS payloads',
    categoryId: 'formatters',
    icon: Minimize2,
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    description: 'Pretty-print and validate XML with configurable indentation',
    categoryId: 'formatters',
    icon: FileCode,
  },
  {
    id: 'yaml-converter',
    name: 'YAML Converter',
    description: 'Format YAML or convert between YAML and JSON',
    categoryId: 'formatters',
    icon: AlignLeft,
  },
  {
    id: 'toml-converter',
    name: 'TOML Converter',
    description: 'Format TOML or convert between TOML and JSON',
    categoryId: 'formatters',
    icon: SlidersHorizontal,
  },
  {
    id: 'js-formatter',
    name: 'JS / TS Formatter',
    description: 'Format JavaScript and TypeScript using Prettier rules',
    categoryId: 'formatters',
    icon: FileJson,
  },
  {
    id: 'csv-viewer',
    name: 'CSV Formatter & Viewer',
    description: 'Parse, view, and reformat CSV with configurable delimiters',
    categoryId: 'formatters',
    icon: Table2,
  },
  {
    id: 'markdown-preview',
    name: 'Markdown Preview',
    description: 'Preview rendered Markdown or format and normalise its syntax',
    categoryId: 'formatters',
    icon: BookOpen,
  },
  {
    id: 'graphql-formatter',
    name: 'GraphQL Formatter',
    description: 'Format GraphQL schemas, queries, mutations, and fragments',
    categoryId: 'formatters',
    icon: Workflow,
  },
  {
    id: 'ini-formatter',
    name: 'INI Formatter',
    description: 'Format INI and config files — normalize separators, sort sections and keys',
    categoryId: 'formatters',
    icon: Settings2,
  },
  {
    id: 'dockerfile-formatter',
    name: 'Dockerfile Formatter',
    description: 'Format Dockerfiles and lint for common mistakes — deprecated instructions, missing version tags, apt hygiene',
    categoryId: 'formatters',
    icon: Container,
  },
  {
    id: 'nginx-formatter',
    name: 'Nginx Config Formatter',
    description: 'Format and normalize Nginx configuration files with consistent indentation',
    categoryId: 'formatters',
    icon: Server,
  },
  {
    id: 'http-headers',
    name: 'HTTP Headers Formatter',
    description: 'Parse and format HTTP request and response headers — sort, normalize casing, table view',
    categoryId: 'formatters',
    icon: Globe,
  },
  {
    id: 'log-formatter',
    name: 'Log Formatter',
    description: 'Parse structured JSON logs (pino, winston, bunyan) into a readable view — filter by level, toggle metadata',
    categoryId: 'formatters',
    icon: ScrollText,
  },
  {
    id: 'base64',
    name: 'Base64 Encoder',
    description: 'Encode or decode Base64 text and convert images to Data URLs',
    categoryId: 'encoders',
    icon: Code2,
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder',
    description: 'Encode and decode URL components safely',
    categoryId: 'encoders',
    icon: Link,
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Inspect JWT header, payload, and expiration client-side',
    categoryId: 'encoders',
    icon: Key,
  },
  {
    id: 'html-entity-coder',
    name: 'HTML Entity Encoder / Decoder',
    description: 'Escape reserved HTML characters or decode named and numeric entities',
    categoryId: 'encoders',
    icon: Ampersand,
  },
  {
    id: 'unicode-escape-coder',
    name: 'Unicode Encoder / Decoder',
    description: 'Convert text to Unicode escape sequences (JS, CSS, Python, U+ notation) and back',
    categoryId: 'encoders',
    icon: Binary,
  },
  {
    id: 'hex-coder',
    name: 'Hex Encoder / Decoder',
    description: 'Convert text to its UTF-8 hexadecimal byte representation and back',
    categoryId: 'encoders',
    icon: Hexagon,
  },
  {
    id: 'number-base-converter',
    name: 'Number Base Converter',
    description: 'Convert integers between binary, octal, decimal, and hexadecimal',
    categoryId: 'encoders',
    icon: Calculator,
  },
  {
    id: 'morse-coder',
    name: 'Morse Code Encoder / Decoder',
    description: 'Convert text to Morse code and back, with word separators',
    categoryId: 'encoders',
    icon: Radio,
  },
  {
    id: 'punycode-coder',
    name: 'Punycode / IDN Encoder / Decoder',
    description: 'Convert internationalized domain names to Punycode ASCII form and back',
    categoryId: 'encoders',
    icon: Languages,
  },
  {
    id: 'quoted-printable-coder',
    name: 'Quoted-Printable Encoder / Decoder',
    description: 'Convert text to Quoted-Printable (RFC 2045) encoding and back',
    categoryId: 'encoders',
    icon: Mail,
  },
  {
    id: 'caesar-cipher',
    name: 'Caesar Cipher / ROT-13',
    description: 'Shift letters by a configurable amount, with a ROT-13 preset',
    categoryId: 'encoders',
    icon: Shuffle,
  },
  {
    id: 'gzip-deflate',
    name: 'Gzip / Deflate Compress & Decompress',
    description: 'Compress and decompress text with Gzip or Deflate entirely in the browser',
    categoryId: 'encoders',
    icon: FileArchive,
  },
  {
    id: 'jwt-builder',
    name: 'JWT Builder',
    description: 'Build and sign JSON Web Tokens with HMAC-SHA256',
    categoryId: 'encoders',
    icon: Signature,
  },
  {
    id: 'mime-type-lookup',
    name: 'MIME Type Lookup',
    description: 'Look up MIME types by file extension, filename, or find extensions for a MIME type',
    categoryId: 'encoders',
    icon: FileSearch,
  },
  {
    id: 'data-url-file-converter',
    name: 'Data URL ↔ File Converter',
    description: 'Convert a file to a Data URL, or decode a Data URL back into a downloadable file',
    categoryId: 'encoders',
    icon: FileUp,
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test regular expressions with live match highlighting',
    categoryId: 'text',
    icon: Search,
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    description: 'Convert text to camelCase, snake_case, PascalCase, and more',
    categoryId: 'text',
    icon: Type,
  },
  {
    id: 'diff-checker',
    name: 'Diff Checker',
    description: 'Compare two text blocks and visualize line differences',
    categoryId: 'text',
    icon: ArrowLeftRight,
  },
  {
    id: 'word-char-counter',
    name: 'Word & Character Counter',
    description: 'Count words, characters, sentences, paragraphs, and lines as you type',
    categoryId: 'text',
    icon: AlignJustify,
  },
  {
    id: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder text by words, sentences, or paragraphs',
    categoryId: 'text',
    icon: WholeWord,
  },
  {
    id: 'text-sorter',
    name: 'Text Sorter',
    description: 'Sort lines alphabetically, numerically, or by length — with dedup and cleanup options',
    categoryId: 'text',
    icon: ArrowUpAZ,
  },
  {
    id: 'text-reverse',
    name: 'Text Reverse',
    description: 'Reverse text by character, word, or line order',
    categoryId: 'text',
    icon: FlipHorizontal2,
  },
  {
    id: 'slug-generator',
    name: 'Slug Generator',
    description: 'Turn a title into a clean, URL-safe slug',
    categoryId: 'text',
    icon: Link2,
  },
  {
    id: 'whitespace-line-cleaner',
    name: 'Whitespace / Line Cleaner',
    description: 'Trim, collapse, and strip whitespace and blank lines from text',
    categoryId: 'text',
    icon: Eraser,
  },
  {
    id: 'string-escape',
    name: 'String Escape / Unescape',
    description: 'Escape or unescape strings for JS, Python, or SQL',
    categoryId: 'text',
    icon: Quote,
  },
  {
    id: 'find-replace',
    name: 'Find & Replace',
    description: 'Find and replace text with plain matching or regex, including capture group substitution',
    categoryId: 'text',
    icon: Replace,
  },
  {
    id: 'line-filter',
    name: 'Line Filter',
    description: 'Keep or remove lines matching a plain-text or regex pattern, like grep',
    categoryId: 'text',
    icon: Filter,
  },
  {
    id: 'column-extractor',
    name: 'Column Extractor',
    description: 'Split delimited text and extract selected columns by index',
    categoryId: 'text',
    icon: Columns3,
  },
  {
    id: 'markdown-to-html',
    name: 'Markdown to HTML Converter',
    description: 'Convert Markdown source into sanitized HTML, with a live preview',
    categoryId: 'text',
    icon: FileCode2,
  },
  {
    id: 'html-to-markdown',
    name: 'HTML to Markdown Converter',
    description: 'Convert HTML markup into clean Markdown syntax',
    categoryId: 'text',
    icon: FileText,
  },
  {
    id: 'ascii-art',
    name: 'Text to ASCII Art',
    description: 'Render short text as blocky ASCII art letters',
    categoryId: 'text',
    icon: Sparkles,
  },
  {
    id: 'levenshtein-distance',
    name: 'Levenshtein Distance Calculator',
    description: 'Compute the edit distance and similarity percentage between two strings',
    categoryId: 'text',
    icon: GitCompareArrows,
  },
  {
    id: 'readability-score',
    name: 'Readability Score',
    description: 'Flesch Reading Ease and Flesch-Kincaid Grade Level for a block of text',
    categoryId: 'text',
    icon: GraduationCap,
  },
  {
    id: 'duplicate-line-remover',
    name: 'Duplicate Line Remover',
    description: 'Remove duplicate lines from text, keeping the first occurrence of each',
    categoryId: 'text',
    icon: ListX,
  },
  {
    id: 'sentence-counter',
    name: 'Sentence Counter',
    description: 'Count sentences and words, and see the average sentence length',
    categoryId: 'text',
    icon: MessageSquareText,
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Compute MD5, SHA-1, SHA-256, and SHA-512 simultaneously',
    categoryId: 'generators',
    icon: Hash,
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Bulk-generate v4 UUIDs with format and delimiter controls',
    categoryId: 'generators',
    icon: Fingerprint,
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert Unix epochs and ISO dates with a live ticker',
    categoryId: 'generators',
    icon: Clock,
  },
  {
    id: 'uuid-versions-generator',
    name: 'UUID v1 / v3 / v5 / v7 Generator',
    description: 'Generate timestamp-based, name-based, and Unix-time UUIDs beyond the standard v4',
    categoryId: 'generators',
    icon: Boxes,
  },
  {
    id: 'ulid-generator',
    name: 'ULID Generator',
    description: 'Generate bulk ULIDs — lexicographically sortable, 128-bit, timestamp-prefixed identifiers',
    categoryId: 'generators',
    icon: Barcode,
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate strong random passwords with configurable length, charset, and entropy display',
    categoryId: 'generators',
    icon: KeyRound,
  },
  {
    id: 'passphrase-generator',
    name: 'Passphrase Generator',
    description: 'Generate memorable passphrases from the BIP39 wordlist, with configurable word count and separator',
    categoryId: 'generators',
    icon: BookText,
  },
  {
    id: 'hmac-generator',
    name: 'HMAC Generator',
    description: 'Compute HMAC-SHA256 and HMAC-SHA512 for a message using a secret key',
    categoryId: 'generators',
    icon: ShieldCheck,
  },
  {
    id: 'totp-generator',
    name: 'TOTP / 2FA Code Generator',
    description: 'Generate time-based one-time passcodes (RFC 6238) from a Base32 secret, with a live countdown',
    categoryId: 'generators',
    icon: TimerReset,
  },
  {
    id: 'bcrypt-tool',
    name: 'Bcrypt Hash & Verify',
    description: 'Hash passwords with bcrypt at a configurable cost factor, and verify a password against an existing hash',
    categoryId: 'generators',
    icon: Lock,
  },
  {
    id: 'argon2-tool',
    name: 'Argon2 Hash & Verify',
    description: 'Hash passwords with Argon2 (RFC 9106) at configurable cost parameters, and verify a password against an existing hash',
    categoryId: 'generators',
    icon: LockKeyhole,
  },
  {
    id: 'rsa-key-pair-generator',
    name: 'RSA Key Pair Generator',
    description: 'Generate an RSA public/private key pair in the browser using the WebCrypto API, exported as PEM',
    categoryId: 'generators',
    icon: KeySquare,
  },
  {
    id: 'certificate-decoder',
    name: 'Certificate Decoder',
    description: 'Decode a PEM-encoded X.509 certificate into human-readable subject, validity, key, and extension fields',
    categoryId: 'generators',
    icon: FileBadge,
  },
  {
    id: 'ssh-fingerprint',
    name: 'SSH Key Fingerprint',
    description: 'Compute the MD5 and SHA256 fingerprints of an OpenSSH public key, client-side',
    categoryId: 'generators',
    icon: Terminal,
  },
  {
    id: 'csrf-token-generator',
    name: 'CSRF Token Generator',
    description: 'Generate a cryptographically random CSRF token with configurable length and encoding',
    categoryId: 'generators',
    icon: ShieldAlert,
  },
  {
    id: 'csp-builder',
    name: 'Content Security Policy Builder',
    description: 'Build a Content-Security-Policy header or meta tag by filling in sources for each directive',
    categoryId: 'generators',
    icon: ShieldHalf,
  },
  {
    id: 'robots-txt-generator',
    name: 'robots.txt Generator',
    description: 'Build a robots.txt file with per-user-agent allow/disallow rules and sitemap references',
    categoryId: 'generators',
    icon: Bot,
  },
  {
    id: 'htaccess-generator',
    name: '.htaccess Generator',
    description: 'Build an Apache .htaccess file — HTTPS/www redirects, custom redirects, error pages, caching, compression, and access rules',
    categoryId: 'generators',
    icon: FileCog,
  },
  {
    id: 'nanoid-generator',
    name: 'Nano ID Generator',
    description: 'Generate bulk Nano IDs with configurable size and alphabet — compact, URL-safe, cryptographically random',
    categoryId: 'generators',
    icon: Dna,
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert between length, weight, temperature, area, and volume units',
    categoryId: 'numbers',
    icon: Ruler,
  },
  {
    id: 'currency-converter',
    name: 'Currency Converter',
    description: 'Convert between world currencies using live exchange rates',
    categoryId: 'numbers',
    icon: Coins,
  },
  {
    id: 'percentage-calculator',
    name: 'Percentage Calculator',
    description: 'Calculate percentages, percent-of values, and percentage change',
    categoryId: 'numbers',
    icon: Percent,
  },
  {
    id: 'aspect-ratio-calculator',
    name: 'Aspect Ratio Calculator',
    description: 'Simplify a width/height ratio and solve for a missing dimension',
    categoryId: 'numbers',
    icon: Proportions,
  },
  {
    id: 'bitwise-calculator',
    name: 'Bitwise Calculator',
    description: 'Compute AND, OR, XOR, NOT, and bit shifts with a binary result view',
    categoryId: 'numbers',
    icon: Cpu,
  },
  {
    id: 'ieee754-visualizer',
    name: 'IEEE 754 Float Visualizer',
    description: 'Break a floating-point number down into its sign, exponent, and mantissa bits',
    categoryId: 'numbers',
    icon: Waves,
  },
  {
    id: 'roman-numeral-converter',
    name: 'Roman Numeral Converter',
    description: 'Convert between Arabic numbers and Roman numerals (1–3999)',
    categoryId: 'numbers',
    icon: Landmark,
  },
  {
    id: 'big-number-calculator',
    name: 'Big Number Calculator',
    description: 'Exact arbitrary-precision integer arithmetic — no floating-point rounding',
    categoryId: 'numbers',
    icon: Sigma,
  },
  {
    id: 'fibonacci-prime-generator',
    name: 'Fibonacci / Prime Sequence Generator',
    description: 'Generate the first N Fibonacci numbers, or list primes up to a limit',
    categoryId: 'numbers',
    icon: Repeat,
  },
  {
    id: 'matrix-calculator',
    name: 'Matrix Calculator',
    description: 'Add, subtract, multiply, transpose matrices, and compute determinant/inverse for square matrices',
    categoryId: 'numbers',
    icon: Grid3x3,
  },
  {
    id: 'statistics-calculator',
    name: 'Statistics Calculator',
    description: 'Compute mean, median, mode, standard deviation, and more from a list of numbers',
    categoryId: 'numbers',
    icon: BarChart3,
  },
  {
    id: 'color-math',
    name: 'Color Math',
    description: 'Mix two colors, and check WCAG contrast ratio and pass/fail levels',
    categoryId: 'numbers',
    icon: Palette,
  },
  {
    id: 'json-to-typescript',
    name: 'JSON to TypeScript Interface Generator',
    description: 'Infer TypeScript interfaces from a JSON payload, including nested objects and arrays',
    categoryId: 'data',
    icon: FileType2,
  },
  {
    id: 'json-to-zod',
    name: 'JSON to Zod Schema Generator',
    description: 'Infer a Zod validation schema from a JSON payload, including nested objects and arrays',
    categoryId: 'data',
    icon: ShieldQuestion,
  },
  {
    id: 'json-to-csv',
    name: 'JSON to CSV Converter',
    description: 'Convert a JSON array of objects into CSV, flattening nested fields with dot notation',
    categoryId: 'data',
    icon: FileSpreadsheet,
  },
  {
    id: 'csv-to-json',
    name: 'CSV to JSON Converter',
    description: 'Convert CSV with a header row into a JSON array of objects, with type coercion for numbers and booleans',
    categoryId: 'data',
    icon: FileJson2,
  },
  {
    id: 'json-path-tester',
    name: 'JSON Path Tester',
    description: 'Evaluate a JSONPath query against a JSON document and inspect the matched values',
    categoryId: 'data',
    icon: Route,
  },
];
